wazo-platform/xivo-dao

- xivo_dao/alchemy/application.py
- xivo_dao/alchemy/linefeatures.py
- xivo_dao/alchemy/tests/test_application.py
- xivo_dao/alchemy/tests/test_linefeatures.py
- xivo_dao/asterisk_conf_dao.py
- xivo_dao/resources/line/dao.py
- xivo_dao/resources/line/persistor.py
- xivo_dao/resources/line/tests/test_dao.py
- xivo_dao/resources/queue/tests/test_dao.py
asterisk_conf: return application_uuid on user sip
fix typo
line_dao: allow di/associate an application
application: add lines relationship
linefeatures: add application_uuid foreignkey
> Pull request for WAZO-891-line-application

- xivo_dao/resources/parking_lot/persistor.py
- xivo_dao/resources/parking_lot/tests/test_dao.py
reason: otherwise, the extension is associated to a ghost parking lot
.... Happy Halloween
> parking_lot: unset extension on delete

- xivo_dao/resources/user/search.py
I missed that during the review of search by multiple UUIDs.
> user: fix python2 compatibility

- xivo_dao/alchemy/groupfeatures.py
- xivo_dao/resources/extension/dao.py
- xivo_dao/resources/extension/tests/test_dao.py
- xivo_dao/tests/test_dao.py
groupfeatures: remove unused deleted column
groupfeatures: remove duplicate number/context columns
group: remove wrong context fix
> Pull request for WAZO-1428-avoid-set-groupfeature-queue-context

- xivo_dao/resources/user/view.py
Depends-on: https://github.com/wazo-platform/xivo-dao/pull/14
> Pull request for WAZO-1436-add-missing-joinedload

- xivo_dao/alchemy/enum.py
enum: remove unused dialaction values
> Pull request for WAZO-1504-remove-unused-value

- xivo_dao/alchemy/incall.py
- xivo_dao/alchemy/tests/test_incall.py
- xivo_dao/resources/extension/fixes.py
- xivo_dao/tests/test_dao.py
tests: avoid to create default dialaction for incall
incall: return destination none when it's null
> Pull request for fix-incall-destination-when-dest-is-deleted

- xivo_dao/alchemy/__init__.py
- xivo_dao/alchemy/all/__init__.py
- xivo_dao/alchemy/pjsip_transport.py
- xivo_dao/alchemy/pjsip_transport_option.py
- xivo_dao/alchemy/tests/test_pjsip_transport.py
- xivo_dao/resources/pjsip_transport/dao.py
- xivo_dao/resources/pjsip_transport/persistor.py
- xivo_dao/resources/pjsip_transport/search.py
- xivo_dao/resources/pjsip_transport/tests/test_dao.py
- xivo_dao/tests/test_dao.py
Depends-On: https://github.com/wazo-platform/xivo-manage-db/pull/36
> WAZO-1613 add the pjsip_transport dao

- xivo_dao/alchemy/call_log.py
Jira-Issue: https://wazo-dev.atlassian.net/browse/WAZO-1707
> call_log: add requested_name column

- xivo_dao/alchemy/conference.py
- xivo_dao/alchemy/dialaction.py
- xivo_dao/alchemy/dialpattern.py
- xivo_dao/alchemy/extension.py
- xivo_dao/alchemy/groupfeatures.py
- xivo_dao/alchemy/incall.py
- xivo_dao/alchemy/line_extension.py
- xivo_dao/alchemy/linefeatures.py
- xivo_dao/alchemy/outcall.py
- xivo_dao/alchemy/parking_lot.py
- xivo_dao/alchemy/queuefeatures.py
- xivo_dao/alchemy/rightcall.py
- xivo_dao/alchemy/rightcallmember.py
- xivo_dao/alchemy/sccpline.py
- xivo_dao/alchemy/schedule.py
- xivo_dao/alchemy/schedulepath.py
- xivo_dao/alchemy/staticiax.py
- xivo_dao/alchemy/staticsip.py
- xivo_dao/alchemy/trunkfeatures.py
- xivo_dao/alchemy/usercustom.py
- xivo_dao/alchemy/userfeatures.py
- xivo_dao/alchemy/useriax.py
- xivo_dao/alchemy/usersip.py
- xivo_dao/resources/group/persistor.py
- xivo_dao/resources/outcall/persistor.py
expire rightcall_members relationship
remove duplicate relationship
set endpoint_custom as viewonly
remove back_populates from viewonly relationship
> Pull request for remove-unpredictable-config

- xivo_dao/alchemy/incall.py
- xivo_dao/resources/incall/persistor.py
- xivo_dao/resources/incall/search.py
- xivo_dao/resources/incall/tests/test_dao.py
incall: add greeting_sound property
incall: fix styling issues
remove unused Dockerfile and test inside docker
use pytest instead nose
Jira-Issue: https://wazo-dev.atlassian.net/browse/WAZO-1738
> Pull request for WAZO-1738-incall-greeting-sound

- xivo_dao/alchemy/staticiax.py
- xivo_dao/alchemy/staticsip.py
- xivo_dao/alchemy/tests/test_trunkfeatures.py
- xivo_dao/alchemy/trunkfeatures.py
- xivo_dao/alchemy/usercustom.py
- xivo_dao/alchemy/useriax.py
- xivo_dao/alchemy/usersip.py
- xivo_dao/asterisk_conf_dao.py
- xivo_dao/resources/endpoint_custom/persistor.py
- xivo_dao/resources/endpoint_iax/persistor.py
- xivo_dao/resources/endpoint_iax/tests/test_dao.py
- xivo_dao/resources/endpoint_sccp/persistor.py
- xivo_dao/resources/endpoint_sip/persistor.py
- xivo_dao/resources/register_iax/persistor.py
- xivo_dao/resources/register_iax/tests/test_dao.py
- xivo_dao/resources/register_sip/persistor.py
- xivo_dao/resources/register_sip/tests/test_dao.py
- xivo_dao/resources/trunk/fixes.py
- xivo_dao/resources/trunk/persistor.py
- xivo_dao/resources/trunk/tests/test_dao.py
- xivo_dao/resources/trunk/tests/test_fixes.py
- xivo_dao/tests/test_asterisk_conf_dao.py
use new trunk endpoint/register columns
trunkfeatures: refactor protocol/id to use endpoint_*_id
Jira-Issue: https://wazo-dev.atlassian.net/browse/WAZO-1779
> Pull request for WAZO-1779-trunkfeatures-endpoints

- xivo_dao/alchemy/linefeatures.py
- xivo_dao/alchemy/trunkfeatures.py
- xivo_dao/resources/endpoint_custom/tests/test_dao.py
- xivo_dao/resources/endpoint_sccp/tests/test_dao.py
- xivo_dao/resources/endpoint_sip/tests/test_dao.py
- xivo_dao/resources/line/dao.py
- xivo_dao/resources/line/fixes.py
- xivo_dao/resources/line/persistor.py
- xivo_dao/resources/line/tests/test_dao.py
- xivo_dao/resources/trunk/dao.py
- xivo_dao/resources/trunk/persistor.py
- xivo_dao/resources/trunk/tests/test_dao.py
- xivo_dao/tests/test_dao.py
linefeatures: remove unused helpers
add dao to associate line/endpoint
trunkfeatures: remove unused helpers
test: add DB_ECHO variable to switch DB log on/off
add dao to associate trunk/endpoint
> Pull request for WAZO-1776-refactor-association-endpoint

- xivo_dao/agent_dao.py
- xivo_dao/agent_status_dao.py
- xivo_dao/line_dao.py
- xivo_dao/resources/pjsip_transport/tests/test_dao.py
- xivo_dao/resources/user/tests/test_dao.py
- xivo_dao/tests/test_agent_dao.py
- xivo_dao/tests/test_agent_status_dao.py
- xivo_dao/tests/test_dao.py
- xivo_dao/tests/test_line_dao.py
> Pull request for WAZO-1644-agent-login-choose-line

- xivo_dao/alchemy/all/__init__.py
- xivo_dao/alchemy/usersip.py
reason: we don't want to remove usersip table for migrated user (to help
to debug)
> revert remove of usersip table

- xivo_dao/alchemy/tenant.py
- xivo_dao/resources/endpoint_sip/tests/test_dao.py
- xivo_dao/tests/test_asterisk_conf_dao.py
this template should only be applied to trunks with a registration
> rename global trunk template

- xivo_dao/asterisk_conf_dao.py
also cast options to list to avoid unecessary INSERT (but not
commited) operation triggered by adding set_var
> WAZO-1989 add joinedload on when generate pjsip.conf

- xivo_dao/alchemy/stat_agent.py
- xivo_dao/alchemy/tests/test_stat_agent.py
- xivo_dao/tests/test_dao.py
the number uses the name which is usually Agent/<number> when the format of the
name does not match None is returned
> stat_agent: add the number property

- xivo_dao/resources/user/search.py
- xivo_dao/resources/user/tests/test_dao.py
reason: allow dird to make max two queries with many numbers
> user: allow to search by multiple exten/mobile

- xivo_dao/alchemy/incall.py
- xivo_dao/resources/extension/fixes.py
- xivo_dao/resources/extension/tests/test_fixes.py
- xivo_dao/resources/incall/search.py
- xivo_dao/resources/incall/tests/test_dao.py
When you search in incall with the API there is no result from the exten fields.
> WAZO-2167 fix search in extension for incall

- xivo_dao/resources/call_log/dao.py
- xivo_dao/resources/call_log/tests/test_dao.py
reason: to be able to deleted associated recordings
> call_log: return deleted call_log_id

- xivo_dao/alchemy/rightcall.py
- xivo_dao/resources/group/tests/test_dao.py
the name is used as a label only, there's no reason to make it unique
> call permission: make name non unique

- xivo_dao/agent_dao.py
- xivo_dao/agent_status_dao.py
- xivo_dao/alchemy/agent_login_status.py
- xivo_dao/alchemy/tests/test_agent_login_status.py
- xivo_dao/tests/test_agent_dao.py
- xivo_dao/tests/test_agent_status_dao.py
I did some cleanup in this branch. I suggest looking at each commit separately to easily see what's important and what is noise. :broom:
> Wazo 2527 agent blf api

- xivo_dao/alchemy/meeting.py
Why:
* Homogenize with database migrations
> meetings: fix cascade directive

- docker-compose.yml
- test-requirements.txt
- zuul.d/roles/xivo-dao-db/tasks/main.yml
- zuul.d/run.yaml
why: to have the latest docker-compose
> use docker-compose from binary instead of python

- xivo_dao/resources/meeting_authorization/persistor.py
- xivo_dao/resources/meeting_authorization/tests/test_dao.py
- xivo_dao/tests/test_dao.py
Why:
* Needed for listing all authorizations oldert than a date
> meeting authorization: allow listing without specified meeting

- xivo_dao/resources/user/dao.py
- xivo_dao/resources/user/persistor.py
- xivo_dao/resources/user/tests/test_dao.py
why: used to count number of subscription of each type
> user: add count_all_by dao

- xivo_dao/alchemy/tests/test_userfeatures.py
- xivo_dao/alchemy/userfeatures.py
Reverts wazo-platform/xivo-dao#181
> Revert "userfeatures: make the voicemail relation CASCADE on delete"

- xivo_dao/alchemy/monitoring.py
- xivo_dao/tests/test_line_dao.py
Depends-On: https://github.com/wazo-platform/xivo-manage-db/pull/182
> remove unsupported dahdi column

- xivo_dao/resources/user/persistor.py
- xivo_dao/resources/user/tests/test_dao.py
- xivo_dao/resources/utils/search.py
- xivo_dao/resources/utils/tests/test_search.py
There was a missing validation for the parameters used by the `search_collated`.
Validation added.
Tests added for `search` and `search_collated`.
> Validate parameters used for user search_collated

- xivo_dao/tests/helpers/fill_leaveempty_calls.sql
- xivo_dao/tests/helpers/fill_simple_calls.sql
- xivo_dao/tests/test_stat_dao.py
- xivo_dao/tests/test_stat_dao_extended.py
https://wazo-dev.atlassian.net/browse/WP-595
* Extracted fill_leaveempty_calls and fill_simple_calls sql function to separate files
* test_stat_dao_extended: updated fill_leaveempty_calls sql function, added test cases
> WP-595 fill_leaveempty_calls

- xivo_dao/resources/utils/search.py
Split code into functions for better reading
> Wp 926 cleanup

- xivo_dao/alchemy/dialaction.py
- xivo_dao/resources/user/view.py
Measured gains on GET /users?recurse=True are >50%
On a 5000 user stack, response drops from 32 seconds to 10.5 seconds
> WAZO-3288: speedups on user listing

- xivo_dao/agent_status_dao.py
- xivo_dao/tests/test_agent_status_dao.py
This reverts commit e86011da2bf5f6c0240511e0b6b71e2c5d7d7a64 and
492f1e744151b78e1f5246e9a77ecc1a747d05e6
> Revert get_status_by_state_interface

- xivo_dao/alchemy/func_key_mapping.py
Depends-On: https://github.com/wazo-platform/xivo-manage-db/pull/208
> Add missing ondelete=cascade fk func_key_mapping/template

- xivo_dao/alchemy/switchboard_member_user.py
Depends-On: https://github.com/wazo-platform/xivo-manage-db/pull/209
> Add ondelete=cascade for switchboard_member

- xivo_dao/resources/incall/dao.py
- xivo_dao/resources/incall/persistor.py
- xivo_dao/resources/incall/strategy.py
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/232
> WP-1059: incalls add relationship preloading

- xivo_dao/alchemy/callerid.py
- xivo_dao/alchemy/contextnumbers.py
- xivo_dao/alchemy/dialpattern.py
- xivo_dao/alchemy/user_line.py
> remove duplicate copyright

- xivo_dao/alchemy/func_key_dest_features.py
- xivo_dao/asterisk_conf_dao.py
- xivo_dao/resources/features/dao.py
- xivo_dao/resources/features/persistor.py
- xivo_dao/resources/features/search.py
- xivo_dao/resources/features/tests/test_dao.py
- xivo_dao/resources/func_key_template/persistor.py
- xivo_dao/resources/func_key_template/tests/test_dao.py
- xivo_dao/tests/test_asterisk_conf_dao.py
> Pull request for WAZO-1870-remove-global-parking

- xivo_dao/alchemy/__init__.py
- xivo_dao/alchemy/all/__init__.py
- xivo_dao/alchemy/func_key_dest_park_position.py
- xivo_dao/alchemy/func_key_dest_parking.py
- xivo_dao/alchemy/parking_lot.py
- xivo_dao/alchemy/tests/test_func_key_dest_park_position.py
- xivo_dao/alchemy/tests/test_func_key_dest_parking.py
- xivo_dao/alchemy/tests/test_parking_lot.py
- xivo_dao/resources/func_key/tests/test_helpers.py
- xivo_dao/resources/func_key_template/persistor.py
- xivo_dao/resources/func_key_template/tests/test_dao.py
why: to convert old hardcoded park position to "new" parking lot table
> Pull request for WP-1276-parking-function-keys

- xivo_dao/helpers/db_manager.py
Helpful for interpreting tests output(differentiating one object instance from another).
> Default __repr__ for sqlalchemy declarative mapping

- etc/xivo-dao/config.yml
- xivo_dao/helpers/db_manager.py
why: easier to troubleshooting
> config: add application_name for db_uri config

- README.md
- tox.ini
- xivo_dao/tests/test_dao.py
- zuul.d/roles/xivo-dao-db/tasks/main.yml
> Pull request for WAZO-3845-tox-passenv

- xivo_dao/alchemy/phone_number.py
- xivo_dao/resources/phone_number/tests/test_dao.py
with check constraint and automatically setting shared along with main
> phone_number: keeping main and shared consistent

- xivo_dao/alchemy/groupfeatures.py
- xivo_dao/resources/group/tests/test_dao.py
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/293
> Wazo 4029 group record toggle

- xivo_dao/alchemy/groupfeatures.py
- xivo_dao/alchemy/queuefeatures.py
- xivo_dao/resources/group/tests/test_dao.py
- xivo_dao/resources/queue/tests/test_dao.py
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/295
> WAZO-4042-default-toggle-record

- xivo_dao/agent_status_dao.py
> agnet_status_dao: fix get_agent_login_status_by_id_for_logoff
