xivo_dao/tests/test_dao.py
test: avoid to generate id
test: allow to pass tenant_uuid when using ItemInserter
=> Pull request for WAZO-940-integration-tests-agentd

xivo_dao/alchemy/tests/test_usersip.py, xivo_dao/alchemy/usersip.py, xivo_dao/resources/endpoint_sip/tests/test_dao.py
Add the username to the EXCLUDE_OPTIONS_CONFD list. Without adding adding the
options to the payload result in the username being reset to None by the
AsteriskOptionsMixin.
=> usersip: allow the username to be specified

xivo_dao/resources/endpoint_sip/persistor.py, xivo_dao/resources/endpoint_sip/tests/test_dao.py
the API used to set the username field input into the name column and did not
allow the user to specify a username.
this change allow the new API to allow the user to create an endpoint with a
name and a username while keeping the same behavior for users using the API the
"old" way.
=> endpoint_sip: set the username to match the name

xivo_dao/resources/access_feature/tests/test_dao.py, xivo_dao/resources/agent/tests/test_dao.py, xivo_dao/resources/call_filter/tests/test_dao.py, xivo_dao/resources/call_permission/tests/test_dao.py, xivo_dao/resources/call_pickup/tests/test_dao.py, xivo_dao/resources/conference/tests/test_dao.py, xivo_dao/resources/context/tests/test_dao.py, xivo_dao/resources/endpoint_sip/tests/test_dao.py, xivo_dao/resources/extension/tests/test_dao.py, xivo_dao/resources/group/tests/test_dao.py, xivo_dao/resources/incall/tests/test_dao.py, xivo_dao/resources/ivr/tests/test_dao.py, xivo_dao/resources/moh/tests/test_dao.py, xivo_dao/resources/outcall/tests/test_dao.py, xivo_dao/resources/paging/tests/test_dao.py, xivo_dao/resources/parking_lot/tests/test_dao.py, xivo_dao/resources/queue/tests/test_dao.py, xivo_dao/resources/register_iax/tests/test_dao.py, xivo_dao/resources/register_sip/tests/test_dao.py, xivo_dao/resources/schedule/tests/test_dao.py, xivo_dao/resources/skill/tests/test_dao.py, xivo_dao/resources/skill_rule/tests/test_dao.py, xivo_dao/resources/switchboard/tests/tests_dao.py, xivo_dao/resources/trunk/tests/test_dao.py, xivo_dao/resources/user/dao.py, xivo_dao/resources/user/search.py, xivo_dao/resources/user/tests/test_dao.py, xivo_dao/resources/utils/search.py, xivo_dao/resources/utils/tests/test_search.py, xivo_dao/resources/voicemail/tests/test_dao.py
user: allow to search with multiple uuid
remove deprecated skip option for search
remove legacy user search
=> Pull request for WAZO-580-search-by-user-uuid

xivo_dao/resources/func_key/hint_dao.py
generate an hint event if there's no user with a funckey pointing at you.
The old behaviour was to create the destination for each user even when there
was no function key. That destination has been removed
=> generate hints for all users

xivo_dao/asterisk_conf_dao.py
```
2020-09-17 10:53:35,051 [12975] (ERROR) (wazo_confgend.confgen): unexpected error raised by handler
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/wazo_confgend/confgen.py", line 96, in _generate_and_cache
content = handler()
File "/usr/lib/python2.7/dist-packages/wazo_confgend/asterisk.py", line 33, in sccp_conf
return self._generate_conf_from_generator(config_generator)
File "/usr/lib/python2.7/dist-packages/wazo_confgend/asterisk.py", line 51, in _generate_conf_from_generator
config_generator.generate(output)
File "/usr/lib/python2.7/dist-packages/wazo_confgend/generators/sccp.py", line 33, in generate
sccp_line_conf.generate(self._sccpline, splitted_settings.line_items, output)
File "/usr/lib/python2.7/dist-packages/wazo_confgend/generators/sccp.py", …
```
=> asterisk_conf_dao: fix missing sccp device ID in line config

xivo_dao/alchemy/all/__init__.py
Why:
* Fresh install does not create the external_app table
=> Pull request for fix-alchemy-all-tables

xivo_dao/asterisk_conf_dao.py, xivo_dao/tests/test_asterisk_conf_dao.py
if a line is associated to an application the context generated by confgend
should be the name of the auto-generated stasis context in asterisk.
The auto-generated context name is `stasis-<app>`
The stasis application name for wazo applications is `wazo-app-<uuid>`
The transfer context is always the context of the line
=> asterisk: pjsip: replace context by the application

xivo_dao/stat_agent_dao.py, xivo_dao/stat_queue_dao.py
reason: it can be hard to debug if flush occur on commit (or via
autoflush). It's good practice to flush after adding an item
=> stat queue/agent: flush session after adding item

xivo_dao/stat_queue_dao.py, xivo_dao/tests/test_stat_queue_dao.py
To reviewer: I don't like what I wrote (architecture and function name), but I haven't a better alternative.
If you have a better idea/approach, please do not hesitate to:
* rename function
* rewrite/propose another architecture
Since we will copy all this logic to agent, I would like to have a more readable code
=> stat_queue: allow to recreate queue with deleted queue name

xivo_dao/asterisk_conf_dao.py, xivo_dao/resources/features/dao.py, xivo_dao/resources/features/persistor.py, xivo_dao/resources/features/search.py, xivo_dao/resources/features/tests/test_dao.py, xivo_dao/resources/func_key_template/persistor.py, xivo_dao/resources/func_key_template/tests/test_dao.py
Why:
* confgend needs this information to generate endpoint variables
Why:
* applicationmap has a value format: name = *3,self,NoOp(my application)
* featuremap has value format: *3
=> WAZO-2059-refactor-online-call-record

xivo_dao/stat_agent_dao.py, xivo_dao/tests/test_stat_agent_dao.py
For now, we don't want to deleted statistic when agent is deleted, but
new agent can use an old deleted agent number. Then to avoid weird issue
with stat generator, deleted agent are renamed and marked as deleted
=> stat_agent: allow to recreate agent with deleted agent number

xivo_dao/stat_agent_dao.py, xivo_dao/tests/test_stat_agent_dao.py
reason: function does not take the same arguments than
create_missing_queues
=> fix copy/paste create_missing_agents

xivo_dao/alchemy/extension.py, xivo_dao/alchemy/schedule.py
reason: line don't need to be automatically removed by the relationship
because the API don't allow to remove extension if a line is associated
See the following commit for more information:
fc3ecf7dceae13a26b3a4aad146d03a9860cfbd8
reason: the schedule_paths is removed by the relationship, then we need
to keep cascade=delete
But viewonly=True is not recommended with cascade=delete
See the following commit for more information:
fc3ecf7dceae13a26b3a4aad146d03a9860cfbd8
=> Pull request for fix-sqlalchemy-incompatibility

xivo_dao/alchemy/all/__init__.py, xivo_dao/alchemy/all/tests/test_all.py
Why:
* It is easy to forget listing a new table in the `all` module
* It can take a while to debug the subsequent errors, so it's better to
check early
Why:
* The new Zuul script is flagging those classes
* They have no good reason to not be exported
=> Pull request for check exported tables

xivo_dao/alchemy/endpoint_sip_options_view.py
Why:
* Alembic script and DAO tables were not the same for endpoint_sip_options_view,
causing tests to fail.
This change addresses the need by:
* Changing union to union_all in endpoint_sip_options_view recursive query
=> WAZO-2185: Fix DAO and migration script diff

xivo_dao/alchemy/endpoint_sip.py, xivo_dao/helpers/db_views.py
Why:
* With recent version of SQLAlchemy (i.e 1.4), passing a string to select_from
without specifying it's type is flagged as an error, because it doesn't
know what to resolve it to.
* Fix wazo-agentd integration tests failing
=> WAZO-2185: Add table to .select_from string

xivo_dao/alchemy/endpoint_sip.py, xivo_dao/alchemy/tests/test_endpoint_sip_options_view.py, xivo_dao/helpers/db_views.py, xivo_dao/helpers/tests/test_materialized_view.py
This PR fixes the implementation of MaterializedView so that it is also compatible with SQLAlchemy >= 1.4
Some integration tests don't pin python package versions hence in this case, when run under SQLAlchemy 1.4.X,
wazo-agentd integration test fails.  
Instead of trying to pin every package in all repos, this fix modifies MaterializedView to be compatible
with SQLAlchemy 1.2 and greater (1.4.27 tested here)
=> WAZO-2185: fix matview sqlalchemy compatibility

xivo_dao/tests/test_stat_agent_dao.py, xivo_dao/tests/test_stat_queue_dao.py
assertEquals is deprecated assertEqual should be used instead. I used hamcrest
and contains_inanyorder to remove the length assertion completely
=> tests: remove deprecation warnings from tests

xivo_dao/alchemy/meeting.py
utcnow() returns the time without the timezone. when inserting the value into a
datetime field with tz the tz is going to be the tz of the stack when
unspecified.  Adding the tz to the now time explicitly removes the ambiguity and
forces postgres to store the right time. Which is going to be the localized time
with the appropriate offset.
=> meeting: set the tz when inserting the meeting date

xivo_dao/alchemy/tests/test_userfeatures.py
Why:
* The test is flaky because the order is undefined
=> tests: fix assertion order

xivo_dao/resources/meeting/dao.py
Why:
* So that guests are not stuck outside a meeting
=> Pull request for WAZO-2793-meeting-authorizations-edit-require

xivo_dao/resources/user_line/persistor.py, xivo_dao/resources/user_line/tests/test_dao.py, xivo_dao/tests/test_dao.py
When a user is a member of a group or a queue the user's main line is the member.
Not any other lines. When deleting a line, only the primary line should trigger a removal from the group or queue.
Extensions group members and agent queue members do not fall into this fix
=> user line: keep group/queue member if secondary line deleted

debian/control
why: xivo-libdao provided the /etc/xivo-dao/config.yml which now is
provided by xivo-libdao-python3. Since we mix lib and config package, we
must add this ugly workaround.
A better solution would be to remove config file from this lib. But it's
out of scope for now
=> debian: add conflict with xivo-libdao

xivo_dao/helpers/db_views.py
also change wording to explain which minimum version is needed (>= 0.33.6)
=> WAZO-2990: modify views comment to remove python2 reference

xivo_dao/alchemy/rightcall.py, xivo_dao/alchemy/rightcallmember.py
Why:
* Users were not loaded automatically with RightCallMembers, meaning there was a fetch for each user.
During testing, eagerloading the users accelerates the query from ~10 sec down to <= 1 sec
Method to test:
1. use a stack with lots of users in a call permission
2. use console to calculate query time for `/api/confd/1.1/callpermissions?recurse=true`
3. apply patch from this commit
4. use console to calculate query time for `/api/confd/1.1/callpermissions?recurse=true`
=> WP-780: use `selectin` eagerloading strategy

xivo_dao/helpers/errors.py
Python 3 enforces that all exceptions be derived from 'BaseException' which is the root of 'Exception' hierarchy. Although this practice isn’t new, it was never enforced.
All the exceptions to be used with 'except' should inherit from Exception class. 'BaseException' to be used as base class only for exceptions that should be handled at top-level like 'SystemExit' or 'KeyboardInterrupt'.
=> Add Exception as parent to FormattedError

xivo_dao/helpers/db_views.py
Why:
* Before, it would also update the view everytime the object would be in the session, including during fetch, which would trigger too many refreshes
=> WAZO-3251: only refresh materialized view when object is updated, created or deleted

xivo_dao/helpers/db_manager.py
Why:
* The option `pool_pre_ping` added recently does exactly that.
=> db_manager: don't ping connection twice

xivo_dao/resources/user/persistor.py, xivo_dao/resources/user/tests/test_dao.py
When users search was processed with limit but without offset, limit parameter was ignored. 
Issue fixed and test added.
=> Fix users search with limit but without offset

xivo_dao/resources/func_key/hint_dao.py, xivo_dao/resources/func_key/tests/test_hint_dao.py
why: when user sharing device state from asterisk, device state is
shared with case sensitive and all custom hints must be in uppercase to
be updated correctly
note: sharing device state is used for horizontal scaling
=> hint: always use uppercase

debian/control
why: When upgrading from Buster to Bullseye, sqlalchemy-utils is
upgraded after wazo services. So if the service use new method, it will
raise an error and fail the installation of this package.
Fortunally, on most case, the command after is dist-upgrade and
will fix thing. But it's still worrying for a sysadmin
=> debian: pin sqlalchemy-utils to prevent upgrade traceback

xivo_dao/alchemy/context.py, xivo_dao/alchemy/contextinclude.py, xivo_dao/alchemy/contextmember.py, xivo_dao/alchemy/contextnumbers.py, xivo_dao/alchemy/tests/test_contextinclude.py, xivo_dao/resources/context/tests/test_dao.py, xivo_dao/resources/tenant/dao.py, xivo_dao/tests/test_asterisk_conf_dao.py, xivo_dao/tests/test_dao.py, xivo_dao/tests/test_user_dao.py
When a tenant was deleted, the context (and their related tables contextnumbers, contextmember, contextinclude) were not deleted.
Depends-On: https://github.com/wazo-platform/xivo-manage-db/pull/204
=> Add missing fks related to context and delete function on tenant DAO

xivo_dao/alchemy/tests/test_voicemail.py, xivo_dao/alchemy/voicemail.py, xivo_dao/resources/user/tests/test_dao.py, xivo_dao/resources/user_voicemail/tests/test_dao.py, xivo_dao/resources/voicemail/tests/test_dao.py, xivo_dao/tests/test_dao.py
When a tenant was deleted, the voicemail was not deleted.
Depends-On: https://github.com/wazo-platform/xivo-manage-db/pull/205
=> Add missing fk for voicemail

xivo_dao/alchemy/linefeatures.py, xivo_dao/alchemy/tests/test_extension.py, xivo_dao/alchemy/user_line.py, xivo_dao/resources/directory_profile/tests/test_dao.py, xivo_dao/resources/endpoint_custom/tests/test_dao.py, xivo_dao/resources/endpoint_sccp/tests/test_dao.py, xivo_dao/resources/extension/tests/test_dao.py, xivo_dao/resources/extension/tests/test_fixes.py, xivo_dao/resources/line/tests/test_dao.py, xivo_dao/resources/line/tests/test_fixes.py, xivo_dao/resources/user_voicemail/tests/test_dao.py, xivo_dao/tests/test_asterisk_conf_dao.py, xivo_dao/tests/test_callfilter_dao.py, xivo_dao/tests/test_dao.py
When a user is deleted, related line(s) must be disassociated
When a line is deleted, related user(s) must be disassociated
When context deleted, related lines must be deleted
Depends-On: https://github.com/wazo-platform/xivo-manage-db/pull/206
=> Add missing fks user_line and linefeatures

zuul.d/roles/xivo-dao-db/tasks/main.yml
why: to see the variable, we must set it before ...
=> zuul: fix debug step to show DB container URL

xivo_dao/alchemy/incall.py, xivo_dao/resources/incall/search.py, xivo_dao/resources/incall/tests/test_dao.py
the user does not know the incall id or the user id. Allowing this only leads to poor user experience when searching for 1001 and ending up with 3 results
incall exten 1001
incall id 1001
incall with a user destination with id 1001
Also searching in user_id is very expensive at the moment
=> incall: avoid searching through ID fields

xivo_dao/resources/user/dao.py, xivo_dao/resources/user/persistor.py, xivo_dao/resources/user/strategy.py, xivo_dao/resources/user/view.py
the configured strategy is now used when no view is specified
When a view is configured the strategy is ignored because we are using a custom query instead of the typical "session.query(User)" that is compatible with the strategies
=> user: move load strategy to the strategy module

xivo_dao/resources/call_permission/strategy.py
outer joins in this context creates cartesian products where the number of rows is multiplied between users, groups and extensions
=> call_permission: selectinload to avoid cartesian product

xivo_dao/alchemy/schedule.py, xivo_dao/alchemy/schedule_time.py
why: allow to return readonly attibute (eg: name) in the API
=> schedule: add relationship for destinations

xivo_dao/alchemy/parking_lot.py, xivo_dao/alchemy/tests/test_parking_lot.py
why: exten is a string and something cannot be cast to int
=> parking_lot: improve validation for in_slots_range

README.md, docker-compose.yml, zuul.d/roles/xivo-dao-db/tasks/main.yml
why: it's now the recommended way to use docker compose
=> use docker compose without hyphen command

.pre-commit-config.yaml, xivo_dao/helpers/sequence_utils.py, xivo_dao/helpers/tests/test_sequence_utils.py, xivo_dao/resources/phone_number/persistor.py, xivo_dao/resources/phone_number/tests/test_dao.py
- **helpers: split_by utility function to split a sequence in two according to a predicate**
- **Added wazo-copyright-check hook in pre-commit config**
- **resources.phone_number: added bulk criteria support for find queries**
=> phone numbers find by number in

xivo_dao/alchemy/trunkfeatures.py, xivo_dao/resources/trunk/search.py, xivo_dao/resources/trunk/tests/test_dao.py
this field will be used to format the X-Wazo-Selected-Caller-ID sent by the UA on an INVITE.
it will eventually be used for any outgoing caller ID once we modify outcalls and user configuration to use the phone-numbers API
=> WAZO-3944-outgoing-caller-id-format

xivo_dao/asterisk_conf_dao.py, xivo_dao/tests/test_asterisk_conf_dao.py
Why: we want both queue and group members to be using usersharedlines, not only
group.
=> [WAZO-3666] Use usersharedlines for queue

xivo_dao/alchemy/incall.py, xivo_dao/resources/incall/dao.py, xivo_dao/resources/incall/persistor.py, xivo_dao/resources/incall/tests/test_dao.py
why: remove deprecated temporary solution for dynamic caller id
superceded by 'phone_number' data model & separate APIs
=> cleanup: remove incalls obsolete code

xivo_dao/alchemy/tests/test_endpoint_sip.py, xivo_dao/alchemy/tests/test_endpoint_sip_options_view.py, xivo_dao/helpers/db_views.py, xivo_dao/resources/endpoint_sip/tests/test_dao.py
why: users import will flush many time at each new user and refreshing
materialized view each time will slowdown (many minutes) the import
=> execute refresh materialized view on commit only

xivo_dao/alchemy/blocklist.py
association_proxy
why: filtering numbers based on tenant
=> blocklist: BlocklistNumber.tenant_uuid

xivo_dao/agent_status_dao.py, xivo_dao/tests/test_agent_status_dao.py
interface to simply consult agent_login_status table for an agent without involving other tables
specifically for cleanup callbacks
=> agent_status_dao: get_agent_login_status_by_id
